CPU_HALF = False
MIN_WORKERS = 1
ENABLE_INTERNET = True

SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 465
SENDER_EMAIL = '123456@gmail.com'
RECEIVER_EMAIL = '654321@gmail.com'
SENDER_PASSWORD = 'QQQAAAWWWEEE'
